name: block-scan
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  build-and-deploy:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout 3m
      - name: set golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod download

      - name: Test with golang tests
        run: go test ./...
