name: block-scan
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  build-and-deploy:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: golangci-lint # bug:Can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"golang.org/x/sync/errgroup\"
#        uses: golangci/golangci-lint-action@v2
#        with:
#          args: --timeout 3m
      - name: set golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.11
      - name: Set GOROOT
        run: |
          echo "GOROOT=$GOROOT_1_17_X64" >> $GITHUB_ENV
      - name: Install dependencies
        run: go mod download

      - name: Test with golang tests
        run: go test ./...
